language: r
warnings_are_errors: true

r_github_packages:
  - wrathematics/RNACI

notifications:
  email:
    on_success: change
    on_failure: change
env:
  - global:
    - _R_CHECK_FORCE_SUGGESTS_=0
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"

sudo: required
